### PR TITLE
Handle errors more gracefully

### LINKED ISSUE #266: Invalid point encountered!
I keep getting the following error pop up. Keeps popping up at incomplete lines of code I am still writing. Any suggestions as to what this is?

```
Error: linter-flake8:: Invalid point encountered! See console for details.
Error: linter-flake8:: Invalid point encountered! See console for details.
    at Error (native)
    at extractRange (/Users/tbansil/.atom/packages/linter-flake8/lib/main.js:73:11)
    at Object.<anonymous> (/Users/tbansil/.atom/packages/linter-flake8/lib/main.js:221:25)
    at undefined.next (native)
    at step (/Users/tbansil/.atom/packages/linter-flake8/lib/main.js:9:273)
```

### LINKED ISSUE #273: "Given editor is not really an editor" after upgrade to Atom  1.12
After I updated to Atom 1.12 when editing Python files I get constant red tooltips saying:

```
Error: linter-flake8:: Invalid point encountered! See console for details.
Error: linter-flake8:: Invalid point encountered! See console for details.
    at Error (native)
    at extractRange (/Users/ludwik/.atom/packages/linter-flake8/lib/main.js:73:11)
    at Object.<anonymous> (/Users/ludwik/.atom/packages/linter-flake8/lib/main.js:221:25)
    at next (<anonymous>)
    at step (/Users/ludwik/.atom/packages/linter-flake8/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

In console I get those errors:

```
message-registry.js [sm]:41Uncaught (in promise) Error: Given editor is not really an editor
    at MessageRegistry.set (/Users/ludwik/.atom/packages/linter/lib/message-registry.js:41:15)
    at /Users/ludwik/.atom/packages/linter/lib/linter.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/ludwik/.atom/packages/linter/lib/linter-registry.js:66:26
```

and

```
main.js [sm]:65linter-flake8:: Invalid point encountered in the attached message ObjectextractRange @ main.js [sm]:65
main.js [sm]:65linter-flake8:: Invalid point encountered in the attached message ObjectextractRange @ main.js [sm]:65
```
screen shot 2016-11-11 at 16 15 04

Tested in Atom 1.12.1 on Mac OS X 10.11.6

### PR DESCRIPTION
**Pull request by Arcanemagus**
Previously we were throwing almost a raw error message to the user. Trap this and generate a "linter message" stating that an invalid point was encountered. Details of the original message are included as traces on the message. In addition, a link is given sending the user to the new issue page with some debugging information, and prompting for code sample.

For example (using the `linter-ui-default` package):

In the panel:
image

Tooltips:
image

And the issue generated when "Report this!" is clicked:
image

Marking this as closing the following issues, since they are all related to invalid points but don't have enough information to act on them. This method should both make it less intrusive to the user, and provide more information where possible.

Closes #271.
Closes #266.
Closes #273. (Although this also mentions another error, I'm not sure if that is actually due to `linter-flake8` as the trace is ambiguous.)

I'm leaving #270 open for the moment as that seems to be where people have converged on these issues.

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -218,20 +222,59 @@ export default {
...
+              type: isErr ? 'Error' : 'Warning',
+              text: `${match[3]} — ${match[5]}`,
+              filePath,
+              range,
+            });
+          } catch (e) {
+            const flake8Version = await getVersionString(execPath);
+            const issueURL = 'https://github.com/AtomLinter/linter-flake8/issues/new';
+            const title = encodeURIComponent(`Flake8 rule '${match[3]}' reported an invalid point`);
+            const body = encodeURIComponent([
```
Comment (steelbrain) [inline lib/main.js]: One function does too much. Can you abstract out all the trace creation logic to a helper?
